version: '2'
services:
  osis-portal:
    build: ./osis-portal/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./osis-portal/:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbit
  osis:
    build: ./osis/
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./osis/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
  rabbit:
    image: rabbitmq
